#
# K2HR3 OpenStack Notification Listener
#
# Copyright 2018 Yahoo! Japan Corporation.
#
# K2HR3 is K2hdkc based Resource and Roles and policy Rules, gathers 
# common management information for the cloud.
# K2HR3 can dynamically manage information as "who", "what", "operate".
# These are stored as roles, resources, policies in K2hdkc, and the
# client system can dynamically read and modify these information.
#
# For the full copyright and license information, please view
# the licenses file that was distributed with this source code.
#
# AUTHOR:   Hirotaka Wakabayashi
# CREATE:   Tue Sep 11 2018 
# REVISION:
#

language: python
dist: xenial
python:
- 3.7
- 3.6
- 3.5

install: make init

script:
- make lint test-with-version coverage docs dist install

deploy:
  provider: pypi
  user: "hiwakaba"
  password: ${TEST_PYPI_TOKEN}
  on:
    tags: true
  server: "https://test.pypi.org/legacy/"
  distributions: "sdist bdist_wheel"
  skip_existing: true

#
# VIM modelines
#
# vim:set ts=4 fenc=utf-8:
#

